version: "3.7"

services:
  mihoteldb:
    image: mysql:5.7.27
    container_name: hoteldb
    restart: always
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: c4d*dBr00t+
      MYSQL_DATABASE: hotel
      MYSQL_USER: juan
      MYSQL_PASSWORD: c4d*dBr00t+
    volumes:
      - ./data/hoteldbd/:/var/lib/mysql2
